try new image
fix tag

check plugins

copy over schema-registry plugin

copy plugins fix

version e

new schema registry smt jar

new smt package

upgrade strimzi to 0.37.0 and kafka 3.5.0

upgrade to strimzi 0.37.0

diff --git a/.github/workflows/build-images.yml b/.github/workflows/build-images.yml
--- a/.github/workflows/build-images.yml
+++ b/.github/workflows/build-images.yml
@@ -59,9 +59,9 @@ jobs:
               echo "Invalid plugin specification: $plugin"
             else
               echo "Detected plugin, attempting to install: $PLUGIN_NAME:$PLUGIN_VERSION"
-              confluent-hub install --no-prompt --worker-configs kafka-connect-distributed.properties --component-dir ./plugins $PLUGIN_NAME:$PLUGIN_VERSION && echo "Installation successful: $PLUGIN_NAME:$PLUGIN_VERSION" || echo "Installation failed: $PLUGIN_NAME:$PLUGIN_VERSION"
-              ls -al ./plugins
+              confluent-hub install --no-prompt --worker-configs kafka-connect-distributed.properties --component-dir ./plugins $PLUGIN_NAME:$PLUGIN_VERSION && echo "Installation successful: $PLUGIN_NAME:$PLUGIN_VERSION" || echo "Installation failed: $PLUGIN_NAME:$PLUGIN_VERSION"              
             fi
+            ls -al ./plugins
           fi
         done < plugins.config
 
